In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split,GridSearchCV ## 資料切分函式庫
from sklearn.pipeline import Pipeline ## 建立機器學習流程的函式庫
from sklearn.preprocessing import StandardScaler ## 資料預處理函式庫
from sklearn.linear_model import LinearRegression, Ridge  ## 線性回歸和 Ridge 回歸模型
from sklearn.ensemble import RandomForestClassifier ## 隨機森林分類器
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score ## 評估指標函式庫
from sklearn.model_selection import GridSearchCV ## 超參數調整函式庫

In [10]:
group_name = {"Group1", "Group2", "Group3", "Group4", "Group5", "Group6"}

for i in range(len(group_name)):
    
    print(list(group_name)[i])

Group2
Group3
Group5
Group1
Group4
Group6


In [2]:
group_name = {"Group1", "Group2", "Group3", "Group4", "Group5", "Group6"}

for group in group_name:
    
    test_data = pd.read_csv(f'./data_set/balance_data/balance_data_{group}.csv')

    test_data['DIQ010'] = test_data['DIQ010'].replace({3.0: 1.0, 2.0: 0.0})

    test_data['GH_GLU_Interact'] = test_data['LBXGH'] * test_data['LBXGLU']
    test_data['UACR_Proxy'] = test_data['URXUMA'] / test_data['LBXSCR']
    test_data['Lipid_Ratio'] = test_data['LBDLDL'] / test_data['LBDHDD']

    X = test_data.drop(columns=['SEQN', 'DIQ010'])
    Y = test_data['DIQ010']

    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_scaled, y_train)

    predictions = model.predict(X_test_scaled)

    score = accuracy_score(y_test, predictions)
    print(f"{group}使用平衡數據集的模型整體準確率: {score * 100:.2f}%\n")

    cm = confusion_matrix(y_test, predictions)
    print("--- 混淆矩陣 (Confusion Matrix) ---")
    print(cm)

    target_names = ['Health (0)', 'Risk (1)'] 
    print("\n--- 分類評估報告 ---")
    print(classification_report(y_test, predictions, target_names=target_names, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=target_names, 
                yticklabels=target_names)
    plt.title('Binary Classification Confusion Matrix (Random Forest)')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')

    if not os.path.exists("./SK_output"): 
        os.makedirs("./SK_output")

    plt.savefig(f"./SK_output/cm_{group}.png")
    plt.clf()

Group2使用平衡數據集的模型整體準確率: 91.28%

--- 混淆矩陣 (Confusion Matrix) ---
[[90  7]
 [10 88]]

--- 分類評估報告 ---
              precision    recall  f1-score   support

  Health (0)       0.90      0.93      0.91        97
    Risk (1)       0.93      0.90      0.91        98

    accuracy                           0.91       195
   macro avg       0.91      0.91      0.91       195
weighted avg       0.91      0.91      0.91       195

Group3使用平衡數據集的模型整體準確率: 75.05%

--- 混淆矩陣 (Confusion Matrix) ---
[[165  91]
 [ 33 208]]

--- 分類評估報告 ---
              precision    recall  f1-score   support

  Health (0)       0.83      0.64      0.73       256
    Risk (1)       0.70      0.86      0.77       241

    accuracy                           0.75       497
   macro avg       0.76      0.75      0.75       497
weighted avg       0.77      0.75      0.75       497

Group5使用平衡數據集的模型整體準確率: 85.59%

--- 混淆矩陣 (Confusion Matrix) ---
[[148  20]
 [ 30 149]]

--- 分類評估報告 ---
              precision    recall  f1-score 

KeyError: 'LBXGLU'

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

In [ ]:
test_data = pd.read_csv('./data_set/balance_data.csv')

test_data['DIQ010'] = test_data['DIQ010'].replace({3.0: 1.0, 2.0: 0.0})

test_data['GH_GLU_Interact'] = test_data['LBXGH'] * test_data['LBXGLU']
test_data['UACR_Proxy'] = test_data['URXUMA'] / test_data['LBXSCR']
test_data['Lipid_Ratio'] = test_data['LBDLDL'] / test_data['LBDHDD']

X = test_data.drop(columns=['SEQN', 'DIQ010'])
Y = test_data['DIQ010']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

predictions = model.predict(X_test_scaled)

score = accuracy_score(y_test, predictions)
print(f"使用平衡數據集的模型整體準確率: {score * 100:.2f}%\n")

cm = confusion_matrix(y_test, predictions)
print("--- 混淆矩陣 (Confusion Matrix) ---")
print(cm)

target_names = ['Health (0)', 'Risk (1)'] 
print("\n--- 分類評估報告 ---")
print(classification_report(y_test, predictions, target_names=target_names, zero_division=0))

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
            xticklabels=target_names, 
            yticklabels=target_names)
plt.title('Binary Classification Confusion Matrix (Random Forest)')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')

if not os.path.exists("./SK_output"): 
    os.makedirs("./SK_output")

plt.savefig("./SK_output/Class_Weighting_balance_data_cm.png")
plt.clf()