In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.model_selection import train_test_split,GridSearchCV ## 資料切分函式庫
from sklearn.pipeline import Pipeline ## 建立機器學習流程的函式庫
from sklearn.preprocessing import StandardScaler ## 資料預處理函式庫
from sklearn.linear_model import LinearRegression, Ridge  ## 線性回歸和 Ridge 回歸模型
from sklearn.ensemble import RandomForestClassifier ## 隨機森林分類器
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score ## 評估指標函式庫
from sklearn.model_selection import GridSearchCV ## 超參數調整函式庫

In [16]:
group = ["Group1", "Group2", "Group3", "Group4", "Group5"]

for group_name in group:

    test_data = pd.read_csv(f'./data_set/balance_data/balance_data_{group_name}.csv')

    test_data['DIQ010'] = test_data['DIQ010'].replace({3.0: 1.0, 2.0: 0.0})

    X = test_data.drop(columns=['SEQN', 'DIQ010'])
    Y = test_data['DIQ010']

    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_scaled, y_train)

    predictions = model.predict(X_test_scaled)

    score = accuracy_score(y_test, predictions)
    print(f"{group_name}使用平衡數據集的模型整體準確率: {score * 100:.2f}%\n")

    cm = confusion_matrix(y_test, predictions)
    print("--- 混淆矩陣 (Confusion Matrix) ---")
    print(cm)

    target_names = ['Health (0)', 'Risk (1)'] 
    print("\n--- 分類評估報告 (Classification Report) ---")
    print(classification_report(y_test, predictions, target_names=target_names, zero_division=0))

    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=target_names, 
                yticklabels=target_names)
    plt.title('Binary Classification Confusion Matrix (Random Forest)')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')

    if not os.path.exists("./SK_output"): 
        os.makedirs("./SK_output")

    plt.savefig(f"./SK_output/cm_{group_name}.png")
    plt.clf()
    print("===========================================================")
    

Group1使用平衡數據集的模型整體準確率: 84.10%

--- 混淆矩陣 (Confusion Matrix) ---
[[92 18]
 [13 72]]

--- 分類評估報告 (Classification Report) ---
              precision    recall  f1-score   support

  Health (0)       0.88      0.84      0.86       110
    Risk (1)       0.80      0.85      0.82        85

    accuracy                           0.84       195
   macro avg       0.84      0.84      0.84       195
weighted avg       0.84      0.84      0.84       195

Group2使用平衡數據集的模型整體準確率: 87.50%

--- 混淆矩陣 (Confusion Matrix) ---
[[65  7]
 [11 61]]

--- 分類評估報告 (Classification Report) ---
              precision    recall  f1-score   support

  Health (0)       0.86      0.90      0.88        72
    Risk (1)       0.90      0.85      0.87        72

    accuracy                           0.88       144
   macro avg       0.88      0.88      0.87       144
weighted avg       0.88      0.88      0.87       144

Group3使用平衡數據集的模型整體準確率: 86.74%

--- 混淆矩陣 (Confusion Matrix) ---
[[122  20]
 [ 17 120]]

--- 分類評估報告 (Cla

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>

<Figure size 800x600 with 0 Axes>